### ISSUE TITLE
API functionality broken 

### ISSUE THREAD

**Issue by smeyernyc** [krayon/stikked#8]
>curl -d text='this is my text' https://pastebin.xxx.com/api/create
curl: (6) Could not resolve host: is
curl: (6) Could not resolve host: my
curl: (3) URL rejected: Bad hostname
https://pastebin.xxx.com/view/01823658

**Comment by krayon** [comment]
These errors are from `curl` complaining about your parameters `is`, `my` etc

This means you've got an issue with your `curl` command, specifically the quotes.

Refer to the `curl` documentation for your specific Operating System and/or your Terminal.

To confirm the API you could probably try testing it with a single word and no quotes.
